### ISSUE TITLE
Duplicated users

### ISSUE THREAD

**Issue by Xylella** [Zrips/CMI#1105]
**Description of issue or feature request:**
Hi, we have a problem on our server with duplicated players. Even if we use the command /cmi duplicates remove from console, players keep duplicating and we don't know what causes this problem. We had Essentials before CMI and duplicated players started to appear as soon as we switched to CMI. With this situation we can't perform some commands on online players because CMI use their duplicate entries and sees them offline. How can we solve this? 

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
ATTENTION! Found n duplicates in database. Same name, different UUID.
```

---

**Cmi Version (using`/cmi version`):** CMI 8.1.0.0

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** CraftBukkit version git-Spigot-642f6d2-fbe3046 (MC: 1.12.29) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by LogGits** [comment]
Somewhat related to #907.

**Comment by Zrips** [comment]
This should be fixed with latest (including todays) updates. Simply remove duplicates with **/cmi removeuser duplicates** and you should no longer get duplicates.

**Comment by xion87** [comment]
The cleeaner now cause crash if trying to clean user (17k duplicates)
https://gist.github.com/xion87/4bcfb74b735240731699ced875025fbd

**Comment by xion87** [comment]
plus still have 14k new duplicates... this start to become anoying and also slow down the server startup

**Comment by Zrips** [comment]
Sorry for inconvenience this one caused to you. Will slower down user removal from database to allow your server to recover from user deletion after each batch. After all this time, there could be that some plugin checks users balances before CMI loads users into cache. At current state it was creating fake accounts when checking and not finding required user, disabled this "feature" which hopefully, once and for all solves this issue. 
Will keep this ticket open. Inform me if duplicates still appearing after next update.

**Comment by xion87** [comment]
still happening: https://gist.github.com/xion87/1d858d7f61fe71ea05e710305afc7d9a

**Comment by Zrips** [comment]
i have noticed that some duplicated users are not being removed in one go, for some strange reason, but it does remove them after couple of tries. Tho it would be more interesting to see if that duplicated user amount increases or its stays at this.

**Comment by xion87** [comment]
yeah i got the same issue i reported that, you have to run the cleanup multiple times before it was all cleaned

**Comment by xion87** [comment]
I found the duplicate lowercase users are caused by the plugin iconomy since it force all names to be in lowercase in his storage, because i am not have any issue with cmi economy, just only the ones where i have iconomy

**Comment by Zrips** [comment]
@Xylella Are you still having this issue? If so, are you using iconomy plugin?

**Comment by Xylella** [comment]
We are not using iconomy, and it seems that there are no new duplicates, but we haven't updated to the latest version yet. As soon as we update CMI we'll inform you if the issue is still happening. Thank you for your time!
