### ISSUE TITLE
Lastonline Filter

### ISSUE THREAD

**Issue by Relaxing9** [Zrips/CMI#4186]
**Description of feature/improvement request:**
Filter on Lastonline command to be similar like in baltop (config option)
---
### Detailed explanation of what it should do, when and in what situation: ###
I know that the /baltop command has a filter which could filter out accounts starting with towny or anything else. What I would like to see is this similar feature on /lastonline because when I type it I also see towny nations/towns in the lastonline list.

### Basic explanation as to why this feature is needed and/or useful to have: ###
Feature is useful to have to fully separate actual users from fake accounts (towny towns/nations).

**Comment by CloudeLecaw** [comment]
If your using /cmi lastonline
then you see towns and nations? @.@
this command  just shows last players

**Comment by Relaxing9** [comment]
> If your using /cmi lastonline
> then you see towns and nations? @.@
> this command just shows last players on the server
> 
> > lastonline (-p:[page])
> > Show played players from last x minutes
> 
> why u see towns there? may a plugin that is linking to show when your town in online?
> 
> So what are you searching for?
> a friendlist like thing? like /friends shows last online and online friend...?
> something like this?

no not looking for /friendlist what I'm looking for is a filter to filter out towns and nations on lastonline, and yes lastonline does show towns and nations of TownyAdvanced...

**Comment by CloudeLecaw** [comment]
What the.. Why that?
Are townies plugin repesent itself as fake player to keep chunks loaded? 

Well then this Problem can be fixed from both sites. So i suggest to infor. The town dev to about this issues

**Comment by Zrips** [comment]
Should be fixed with next update

**Comment by Relaxing9** [comment]
> Should be fixed with next update

It is removed however I see this now (blank pages of all the fake accounts on /lastonline command invocation)
![image](https://user-images.githubusercontent.com/41935047/93026527-831fe980-f5d4-11ea-8e53-9446b6d1b7b9.png)

**Comment by Zrips** [comment]
next version should show correct count of pages excluding fake ones.

**Comment by Relaxing9** [comment]
> next version should show correct count of pages excluding fake ones.

![image](https://user-images.githubusercontent.com/41935047/93658647-83bce380-fa0b-11ea-874f-5597b5300c9c.png)

Strange it took out 1 page but I still see blank pages.........
