### ISSUE TITLE
Sign Edit - Removing Text on Signs

### ISSUE THREAD

**Issue by rockit7** [Zrips/CMI#6860]
**Description of issue:**
When you shift, and right click a sign to edit it. It removes the text already on the sign. 
```
---

**Cmi Version (using`/cmi version`):** 
9.1.4.3
**Server Type (Spigot/Paperspigot/etc):** 
Purpur
**Server Version (using `/ver`):** 
Purpur 1613 - Latest

**Comment by CloudeLecaw** [comment]
This also happens with paper, i think it might be an issue since 1.18.x

**Comment by PanetiX** [comment]
yep, same issue on us, too

**Comment by mrfloris** [comment]
Not a bug with CMI. And should now be fixed, check your servers again.

**Comment by PanetiX** [comment]
> Not a bug with CMI. And should now be fixed, check your servers again. Restarting your launcher and client will resolve this.

No, still does not work!

**Comment by rockit7** [comment]
> Not a bug with CMI. And should now be fixed, check your servers again. Restarting your launcher and client will resolve this.

How can it now be a bug when 4 others have mentioned the same problem? What launcher are you using? Are you using the latest version of CMI? What jar are you using? Is is the latest jar? This reply really is unhelpful.

**Comment by PanetiX** [comment]
> 

I use the latest CMI Version and Minecraft 1.18.1
I restarted Server, Launcher couple of times and the bug is still present for all users on our server. Launcher version doesnt matter. So how this will be a launcher problem? Past days ago it worked perfect with the same launcher :D

**Comment by mrfloris** [comment]
> > Not a bug with CMI. And should now be fixed, check your servers again. Restarting your launcher and client will resolve this.
> 
> How can it now be a bug when 4 others have mentioned the same problem? What launcher are you using? Are you using the latest version of CMI? What jar are you using? Is is the latest jar? This reply really is unhelpful.

It even happens on servers with other plugins that aren't CMI, or don't even have CMI installed. It's caused by a Paper bug + Mojang backend issue, from what I was told by people from the Paper team. I went to check all my servers, and I went to three servers who had the issue reported to me in a DM, and it's fixed on all of them. 

https://www.reddit.com/r/realms/comments/udvjz8/realm_text_not_working/

https://bugs.mojang.com/browse/REALMS-10191

https://github.com/PaperMC/Paper/commit/6f5e6c60d397058d89892862bd194773d1695315

etc.

It's dealt with client-side, so at Mojangs end. no jar files need to get updated. Using third party launchers or clients might probably not fix it unless they perhaps update, I don't know. Vanille Launcher and vanilla client here, restarted them this morning and issue went away. 

Everything I tested was on latest paper 1.18.2 jar, and latest cmi/cmilib (even though it doesn't matter which cmi/cmilib , since it has nothing to do with cmi really, it happens on servers without plugins installed even from tests i did yesterday and today. And yes, those test servers (checked 15 minutes ago) also show content in various things again like signs, and sign edit with cmi on them works fine again as well when i add cmi to them. 

You're free to not believe me, but there's nothing zrips can probably do about this, it's not caused by cmi.

**Comment by mrfloris** [comment]
This also looks promising and has some extra information about it;
https://github.com/PaperMC/Paper/pull/7777

**Comment by lordofpipes** [comment]
For anyone needing a quick and dirty fix, I've written this open source plugin to auto-fix sign NBT data. Currently being used in production on two big servers so I assume the method used is sane - https://github.com/UltraVanilla/cleanupstupidmojangshit

https://github.com/PaperMC/Paper/pull/7777 is another fix, once it's ready you can use it instead of my fixer plugin.

**Comment by mrfloris** [comment]
Thank you lordofpipes, that will help some servers that notice having this. Hopefully, we won't need it soon as Paper's actively working on a fix that we can all upgrade to.

People that do want to use these fixes and suggestions, don't forget to make a full backup of your server first, before making any changes to it. It's not like there's an undo button for things that are parsed.

**Comment by PanetiX** [comment]
Updated Paper to latest version now and it work's :)
Now we need to replace ALL signs who is placed with AdvancedRegionMarket and that are a lot :(

**Comment by mrfloris** [comment]
> Updated Paper to latest version now and it work's :) Now we need to replace ALL signs who is placed with AdvancedRegionMarket and that are a lot :(

I would wait until paper's latest build has this fix, so when chunks get loaded they get updated and the problem fixes itself.

**Comment by mrfloris** [comment]
paper has a new build out that should address this, pls test

**Comment by CloudeLecaw** [comment]
We updated to latest Paper today and yes i can agree its fixed :)

**Comment by arturek1666** [comment]
The 1.17.1 is not fixed sadly, as signs not showing text at all and when trying to edit it it's going blank
