### ISSUE TITLE
Failed to load util command!

### ISSUE THREAD

**Issue by IORIqwe** [Zrips/CMI#7770]
### Description of Issue

just started clear server with cmi and cmilib on spigot 1.19.4 

### Version Information

```shell
9.5.0.4
```

### Errors

```shell
[07:15:19] [Server thread/INFO]:   Failed to load util command!
[07:15:19] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/bukkit/entity/TextDisplay$TextAligment
[07:15:19] [Server thread/WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[07:15:19] [Server thread/WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[07:15:19] [Server thread/WARN]:        at com.Zrips.CMI.commands.CommandsHandler.getClass(CommandsHandler.java:679)
[07:15:19] [Server thread/WARN]:        at com.Zrips.CMI.commands.CommandsHandler.fillCommands(CommandsHandler.java:642)
[07:15:19] [Server thread/WARN]:        at com.Zrips.CMI.CMI.onEnable(CMI.java:1518)
[07:15:19] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[07:15:19] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[07:15:19] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[07:15:19] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:533)
[07:15:19] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:447)
[07:15:19] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589)
[07:15:19] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[07:15:19] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[07:15:19] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:975)
[07:15:19] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[07:15:19] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[07:15:19] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.TextDisplay$TextAligment
[07:15:19] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[07:15:19] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[07:15:19] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[07:15:19] [Server thread/WARN]:        ... 16 more
[07:15:19] [Server thread/INFO]:   Failed to load util command!
[07:15:19] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/bukkit/entity/TextDisplay$TextAligment
[07:15:19] [Server thread/WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[07:15:19] [Server thread/WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[07:15:19] [Server thread/WARN]:        at com.Zrips.CMI.commands.CommandsHandler.getClass(CommandsHandler.java:679)
[07:15:19] [Server thread/WARN]:        at com.Zrips.CMI.commands.CommandsHandler.fillCommands(CommandsHandler.java:642)
[07:15:19] [Server thread/WARN]:        at com.Zrips.CMI.CMI.onEnable(CMI.java:1518)
[07:15:19] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[07:15:19] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[07:15:19] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[07:15:19] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:533)
[07:15:19] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:447)
[07:15:19] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589)
[07:15:19] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[07:15:19] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[07:15:19] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:975)
[07:15:19] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[07:15:19] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[07:15:19] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.TextDisplay$TextAligment
[07:15:19] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[07:15:19] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[07:15:19] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[07:15:19] [Server thread/WARN]:        ... 16 more
[07:15:20] [Server thread/INFO]:   Failed to load util command!
[07:15:20] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/bukkit/entity/TextDisplay$TextAligment
[07:15:20] [Server thread/WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[07:15:20] [Server thread/WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[07:15:20] [Server thread/WARN]:        at com.Zrips.CMI.commands.CommandsHandler.getClass(CommandsHandler.java:679)
[07:15:20] [Server thread/WARN]:        at com.Zrips.CMI.commands.CommandsHandler.fillCommands(CommandsHandler.java:642)
[07:15:20] [Server thread/WARN]:        at com.Zrips.CMI.CMI.onEnable(CMI.java:1518)
[07:15:20] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[07:15:20] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[07:15:20] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[07:15:20] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:533)
[07:15:20] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:447)
[07:15:20] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589)
[07:15:20] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[07:15:20] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[07:15:20] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:975)
[07:15:20] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[07:15:20] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[07:15:20] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.TextDisplay$TextAligment
[07:15:20] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[07:15:20] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[07:15:20] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[07:15:20] [Server thread/WARN]:        ... 16 more
[07:15:20] [Server thread/INFO]:   Failed to load util command!
[07:15:20] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/bukkit/entity/TextDisplay$TextAligment
[07:15:20] [Server thread/WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[07:15:20] [Server thread/WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[07:15:20] [Server thread/WARN]:        at com.Zrips.CMI.commands.CommandsHandler.getClass(CommandsHandler.java:679)
[07:15:20] [Server thread/WARN]:        at com.Zrips.CMI.commands.CommandsHandler.fillCommands(CommandsHandler.java:642)
[07:15:20] [Server thread/WARN]:        at com.Zrips.CMI.CMI.onEnable(CMI.java:1518)
[07:15:20] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[07:15:20] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[07:15:20] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[07:15:20] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:533)
[07:15:20] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:447)
[07:15:20] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589)
[07:15:20] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[07:15:20] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[07:15:20] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:975)
[07:15:20] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[07:15:20] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[07:15:20] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.TextDisplay$TextAligment
[07:15:20] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[07:15:20] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[07:15:20] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[07:15:20] [Server thread/WARN]:        ... 16 more
[07:15:20] [Server thread/INFO]:   Failed to load util command!
[07:15:20] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/bukkit/entity/TextDisplay$TextAligment
[07:15:20] [Server thread/WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[07:15:20] [Server thread/WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[07:15:20] [Server thread/WARN]:        at com.Zrips.CMI.commands.CommandsHandler.getClass(CommandsHandler.java:679)
[07:15:20] [Server thread/WARN]:        at com.Zrips.CMI.commands.CommandsHandler.fillCommands(CommandsHandler.java:642)
[07:15:20] [Server thread/WARN]:        at com.Zrips.CMI.CMI.onEnable(CMI.java:1518)
[07:15:20] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[07:15:20] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[07:15:20] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[07:15:20] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:533)
[07:15:20] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:447)
[07:15:20] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589)
[07:15:20] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[07:15:20] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[07:15:20] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:975)
[07:15:20] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[07:15:20] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[07:15:20] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.TextDisplay$TextAligment
[07:15:20] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[07:15:20] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[07:15:20] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[07:15:20] [Server thread/WARN]:        ... 16 more
[07:15:20] [Server thread/INFO]:   Failed to load util command!
[07:15:20] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/bukkit/entity/TextDisplay$TextAligment
[07:15:20] [Server thread/WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[07:15:20] [Server thread/WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[07:15:20] [Server thread/WARN]:        at com.Zrips.CMI.commands.CommandsHandler.getClass(CommandsHandler.java:679)
[07:15:20] [Server thread/WARN]:        at com.Zrips.CMI.commands.CommandsHandler.fillCommands(CommandsHandler.java:642)
[07:15:20] [Server thread/WARN]:        at com.Zrips.CMI.CMI.onEnable(CMI.java:1518)
[07:15:20] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[07:15:20] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[07:15:20] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[07:15:20] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:533)
[07:15:20] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:447)
[07:15:20] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589)
[07:15:20] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[07:15:20] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[07:15:20] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:975)
[07:15:20] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[07:15:20] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[07:15:20] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.TextDisplay$TextAligment
[07:15:20] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[07:15:20] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[07:15:20] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[07:15:20] [Server thread/WARN]:        ... 16 more
```

### Relevant Plugins

Vault 1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
Does it also appear with CMI 9.5.0.6? and CMILIB 1.2.5.3?

**Comment by IORIqwe** [comment]
> Does it also appear with CMI 9.5.0.6? and CMILIB 1.2.5.3?

Yes, at first I did everything on CMI 9.5.0.6 and CMILIB 1.2.5.3, then checked on older versions

**Comment by CloudeLecaw** [comment]
pls dont forget to give us the full output of cmi version its needed.
i aspect its not 1.19.4 Paper.. we are using this version and the issue seems not to appear there.

So please attach the full output.

**Comment by CloudeLecaw** [comment]
would you mind giving paper a quick try?
Im asking becasue we didnt see this issue on our server that is a paper 1.19.4 one..

**Comment by IORIqwe** [comment]
`[08:49:07] [Server thread/INFO]: [CMI] Enabling CMI v9.5.0.6
[08:49:07] [Server thread/INFO]: ┏━━━┓ ┏━┓┏━┓ ┏━━┓[m
[08:49:07] [Server thread/INFO]: ┃┏━┓┃ ┃ ┗┛ ┃ ┗┫┣┛[m
[08:49:07] [Server thread/INFO]: ┃┃ ┗┛ ┃┏┓┏┓┃  ┃┃ [m
[08:49:07] [Server thread/INFO]: ┃┃ ┏┓ ┃┃┃┃┃┃  ┃┃ [m
[08:49:07] [Server thread/INFO]: ┃┗━┛┃ ┃┃┃┃┃┃ ┏┫┣┓[m
[08:49:07] [Server thread/INFO]: ┗━━━┛ ┗┛┗┛┗┛ ┗━━┛[m
[08:49:07] [Server thread/INFO]: _______________________________________________________[m
[08:49:08] [Server thread/INFO]:   [0;36;22m[0;37;1m58 [0;32;22mEnabled [0;36;22mand [0;37;1m0 [0;33;1mDisabled [0;36;22mmodules[m
[08:49:08] [Server thread/INFO]:   [0;36;22mPermission plugin: [0;35;22mLuckPerms5.4.40[m
[08:49:08] [Server thread/INFO]:   [0;36;22mInitialized Cipher256 AES[m
[08:49:08] [Server thread/INFO]:   [0;36;22m[0;31;1mFailed to load util command![m
[08:49:08] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/bukkit/entity/TextDisplay$TextAligment
[08:49:08] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[08:49:08] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[08:49:08] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.getClass(CommandsHandler.java:679)
[08:49:08] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.fillCommands(CommandsHandler.java:642)
[08:49:08] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1518)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:533)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:447)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:975)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[08:49:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[08:49:08] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.TextDisplay$TextAligment
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[08:49:08] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[08:49:08] [Server thread/WARN]: 	... 16 more
[08:49:08] [Server thread/INFO]:   [0;36;22m[0;31;1mFailed to load util command![m
[08:49:08] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/bukkit/entity/TextDisplay$TextAligment
[08:49:08] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[08:49:08] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[08:49:08] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.getClass(CommandsHandler.java:679)
[08:49:08] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.fillCommands(CommandsHandler.java:642)
[08:49:08] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1518)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:533)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:447)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:975)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[08:49:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[08:49:08] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.TextDisplay$TextAligment
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[08:49:08] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[08:49:08] [Server thread/WARN]: 	... 16 more
[08:49:08] [Server thread/INFO]:   [0;36;22m[0;31;1mFailed to load util command![m
[08:49:08] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/bukkit/entity/TextDisplay$TextAligment
[08:49:08] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[08:49:08] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[08:49:08] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.getClass(CommandsHandler.java:679)
[08:49:08] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.fillCommands(CommandsHandler.java:642)
[08:49:08] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1518)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:533)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:447)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:975)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[08:49:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[08:49:08] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.TextDisplay$TextAligment
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[08:49:08] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[08:49:08] [Server thread/WARN]: 	... 16 more
[08:49:08] [Server thread/INFO]:   [0;36;22m[0;31;1mFailed to load util command![m
[08:49:08] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/bukkit/entity/TextDisplay$TextAligment
[08:49:08] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[08:49:08] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[08:49:08] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.getClass(CommandsHandler.java:679)
[08:49:08] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.fillCommands(CommandsHandler.java:642)
[08:49:08] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1518)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:533)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:447)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:975)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[08:49:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[08:49:08] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.TextDisplay$TextAligment
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[08:49:08] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[08:49:08] [Server thread/WARN]: 	... 16 more
[08:49:08] [Server thread/INFO]:   [0;36;22m[0;31;1mFailed to load util command![m
[08:49:08] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/bukkit/entity/TextDisplay$TextAligment
[08:49:08] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[08:49:08] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[08:49:08] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.getClass(CommandsHandler.java:679)
[08:49:08] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.fillCommands(CommandsHandler.java:642)
[08:49:08] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1518)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:533)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:447)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:975)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[08:49:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[08:49:08] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.TextDisplay$TextAligment
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[08:49:08] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[08:49:08] [Server thread/WARN]: 	... 16 more
[08:49:08] [Server thread/INFO]:   [0;36;22m[0;31;1mFailed to load util command![m
[08:49:08] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/bukkit/entity/TextDisplay$TextAligment
[08:49:08] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[08:49:08] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[08:49:08] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.getClass(CommandsHandler.java:679)
[08:49:08] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.fillCommands(CommandsHandler.java:642)
[08:49:08] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1518)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:533)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:447)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:975)
[08:49:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[08:49:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[08:49:08] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.TextDisplay$TextAligment
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[08:49:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[08:49:08] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[08:49:08] [Server thread/WARN]: 	... 16 more
[08:49:08] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m60[0;36;22m) [0;37;22mregular alias [0;36;22minto memory. [0;33;22mTook [0;33;1m28[0;33;22mms[m
[08:49:08] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m1[0;36;22m) [0;37;22mcustom text's [0;36;22minto memory. [0;33;22mTook [0;33;1m2[0;33;22mms[m
[08:49:08] [Server thread/INFO]:   [0;36;22m3.41.0 data base type detected[m
[08:49:08] [Server thread/INFO]:   [0;36;22mStarted [0;37;22mSqLite [0;36;22mdata base. Took [0;33;22m300ms[m
[08:49:08] [Server thread/INFO]: [CMI] Vault was found but economy engine is missing. Use one from list provided in https://dev.bukkit.org/bukkit-plugins/vault/[m
[08:49:08] [Server thread/INFO]: [CMI] Alternatively you can enable CMI economy in config.yml file[m
[08:49:08] [Server thread/INFO]:   [0;36;22m[0;31;1mVault was found but not economy plugin, you will have limited economy support[m
[08:49:08] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m5[0;36;22m) [0;37;22mwarning categories [0;36;22minto memory. [0;33;22mTook [0;33;1m0[0;33;22mms[m
[08:49:08] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m3[0;36;22m) [0;37;22mwarning commands [0;36;22minto memory. [0;33;22mTook [0;33;1m0[0;33;22mms[m
[08:49:08] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m142[0;36;22m) [0;37;22mcustom mob heads [0;36;22minto memory. [0;33;22mTook [0;33;1m12[0;33;22mms[m
[08:49:08] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m0[0;36;22m) [0;37;22mcooldowns [0;36;22minto memory. [0;33;22mTook [0;33;1m21[0;33;22mms[m
[08:49:08] [Server thread/INFO]:   [0;36;22mInitializing BungeeCord[m
[08:49:08] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m5[0;36;22m) [0;37;22mkits [0;36;22minto memory. [0;33;22mTook [0;33;1m23[0;33;22mms[m
[08:49:08] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m7[0;36;22m) [0;37;22mranks [0;36;22minto memory. [0;33;22mTook [0;33;1m7[0;33;22mms[m
[08:49:08] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m8[0;36;22m) [0;37;22mplaytime rewards [0;36;22minto memory. [0;33;22mTook [0;33;1m2[0;33;22mms[m
[08:49:08] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m0[0;36;22m) [0;37;22mplayer data [0;36;22minto memory. [0;33;22mTook [0;33;1m6[0;33;22mms[m
[08:49:08] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m0[0;36;22m) [0;37;22mplaytime records [0;36;22minto memory. [0;33;22mTook [0;33;1m0[0;33;22mms[m
[08:49:08] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m0[0;36;22m) [0;37;22mplaytime reward records [0;36;22minto memory. [0;33;22mTook [0;33;1m1[0;33;22mms[m
[08:49:08] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m0[0;36;22m) [0;37;22mcustom alias [0;36;22minto memory. [0;33;22mTook [0;33;1m1[0;33;22mms[m
[08:49:09] [Server thread/INFO]:   [0;36;22mRegistered events. Took [0;33;22m47ms[m
[08:49:09] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m0[0;36;22m) [0;37;22mevent action commands [0;36;22minto memory. [0;33;22mTook [0;33;1m4[0;33;22mms[m
[08:49:09] [Server thread/INFO]:   [0;36;22mUpdated (EN) language file. Took [0;33;22m78ms[m
[08:49:09] [Server thread/INFO]:   [0;36;22mUpdated (UA) language file. Took [0;33;22m50ms[m
[08:49:09] [Server thread/WARN]: [CMILib] Loaded class com.Zrips.CMI.Containers.Snd from CMI v9.5.0.6 which is not a depend or softdepend of this plugin.
[08:49:09] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m245[0;36;22m) [0;37;22mworth values [0;36;22minto memory. [0;33;22mTook [0;33;1m93[0;33;22mms[m
[08:49:09] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: cmi [9.5.0.6]
[08:49:09] [Server thread/INFO]:   [0;36;22mPlaceholderAPI hooked.[m
[08:49:09] [Server thread/INFO]:   [0;36;22mPlaceholderAPI was found - Enabling capabilities.[m
[08:49:09] [Server thread/INFO]:   [0;36;22mStarting world timer.[m
[08:49:09] [Server thread/INFO]:   [0;36;22mInitializing world manager.[m
[08:49:09] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m4[0;36;22m) [0;37;22mschedules [0;36;22minto memory. [0;33;22mTook [0;33;1m7[0;33;22mms[m
[08:49:09] [Server thread/INFO]:   [0;36;22mLoaded GeoIP[m
[08:49:09] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m0[0;36;22m) [0;37;22mskin cache entries [0;36;22minto memory. [0;33;22mTook [0;33;1m0[0;33;22mms[m
[08:49:09] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m0[0;36;22m) [0;37;22mArmorStand templates [0;36;22minto memory. [0;33;22mTook [0;33;1m0[0;33;22mms[m
[08:49:09] [Server thread/INFO]:   [0;36;22mVersion [0;37;22m9.5.0.6 [0;36;22mhas been enabled[m
[08:49:09] [Server thread/INFO]: [0;37;22m‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾[m` full output, I will try now paper

**Comment by IORIqwe** [comment]
So this problem doesn't exist on paper. Well, okay, I'll do it on paper, it's even better :). For me, this issue is resolved.

**Comment by IORIqwe** [comment]
![image](https://user-images.githubusercontent.com/130630674/231671247-6c6148a3-7504-47b1-b92d-086feb2d218b.png)
here are the files that were generated on paper, is everything correct?

**Comment by CloudeLecaw** [comment]
yes
in 9.5.0.x the other ymls moved to Saved and Settings Folder

**Comment by Zrips** [comment]
Issue originated from latest 1.19.4 server versions, update to latest versions of CMI and your server and it should be fixed.

**Comment by KoNekoD** [comment]
The problem is still active

**Comment by KoNekoD** [comment]
![image](https://github.com/Zrips/CMI/assets/108808201/4e516101-6561-401a-971d-576d41778ef2)

**Comment by CloudeLecaw** [comment]
your using chat bubbles?

you Updates to 9.6.1.3 because error still sown   ur using versiom 9.5.0.1

if you dont wanr to use chTbubbles you can disable it in chat.yml
