### ISSUE TITLE
Hologram Interaction and Collision

### ISSUE THREAD

**Issue by mario414x** [Zrips/CMI#8189]
### Description of Issue

Hello! Everytime I startup my server, holograms need an additional /cmi reload to work properly. I have tested this with and without plugins and I already reported it on discord. I have recorded a video for this: https://youtu.be/BXSKHXsEASc

Also, it would be great if you could add something that disableds collision between players and holograms, like many other plugins. It would be something like /cmi playercollision.

### Version Information

```shell
Running CMI-9.6.6.0 on the video. Updating to the latest CMI-9.6.7.0 didn't help. Server version: Purpur-1428 (1.17.1).
```

### Errors

```shell
No errors in logs.
```

### Relevant Config Sections

```yaml
Default CMI configuration.
```

### Relevant Plugins

Tested only with couple of plugins installed and the bug persists: ViaVersion-4.8.1, CMI-9.6.6.0, CMILib1.4.2.1, Multiverse-Core-4.3.1

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Duplicated holograms should be fixed or atleast mitigated to appear less frequently if there is another issue i'm not aware of.
For interaction issue, could you send example of your hologram including those buttons? Would be 3 hologram records from holograms file or just send me entire file. Did some testing on pupur 1.17.1 and everything looked to be working, so something specific with your specific setup is going on

**Comment by mario414x** [comment]
https://mclo.gs/pJv8Mtr

**Comment by Zrips** [comment]
Still can't reproduce.
Few things to try out. Test without any other plugins, especially ViaVersion as that one tends to break things. Try entering game mode 3, aka spectator which should start showing armor stands on that hologram. Check if you can see slime mob when you hover over buttons. 
I can see some errors from your video, could you send startup logs in case there are startup issues which cause this bug? 
Side thing, you can increase buttons interaction area by going into holograms editor, then interaction section and setting particle extra width to something like 0.15 which should give you a lot better results.

**Comment by mario414x** [comment]
I can't run my server without viaversion. I have mentioned all plugins used when this error occurs, above "Tested only with couple of plugins installed and the bug persists: ViaVersion-4.8.1, CMI-9.6.6.0, CMILib1.4.2.1, Multiverse-Core-4.3.1"
